<?php $pageTitle='エギングギアラボ｜条件から選ぶ、エギングギア。';$pageDescription='季節・潮・風・水深・地形から、最適なエギ・ロッド・リールを逆引きするエギングギア専門メディア。';require __DIR__.'/partials/header.php';?>
<div class="opening" id="opening" role="dialog" aria-label="サイトイントロ"><video class="opening__video" autoplay muted playsinline loop poster="/assets/visuals/hero-depth.svg"><source src="/assets/video/opening.mp4" type="video/mp4"></video><div class="opening__inner"><div class="opening__scan" aria-hidden="true"><span>WIND</span><span>DEPTH</span><span>CURRENT</span></div><p class="opening__title">EGING GEAR LAB</p><p>READ THE WATER / CHOOSE THE GEAR</p><button data-skip type="button">ENTER</button></div></div>
<main id="main">
<section class="hero"><div class="hero__visual"><img src="/assets/visuals/hero-depth.svg" alt=""></div><div class="hero__content"><p class="eyebrow">Condition driven tackle selection</p><h1 class="display">条件から<br><span class="stroke">選ぶ。</span></h1><div class="hero__sub"><p>季節、風、潮、水深、地形。先に海の条件を読む。そこからエギ、ロッド、ラインを逆算する。おすすめ順ではなく、理由から道具を選ぶためのエギングギア専門メディアです。</p><div class="hero__actions"><a class="cta cta--primary" href="#condition">条件から診断</a><a class="cta" href="/gear.php">ギアを探す</a></div></div></div></section>
<div class="marquee"><div class="marquee__track"><span>SEASON</span><span>WIND</span><span>CURRENT</span><span>DEPTH</span><span>FIELD</span><span>SIZE</span><span>SEASON</span><span>WIND</span><span>CURRENT</span><span>DEPTH</span><span>FIELD</span><span>SIZE</span></div></div>
<section class="section" id="condition"><div class="condition-stage"><div class="condition-copy reveal"><div><span class="kicker">01 / CONDITION SELECTOR</span><h3>海から、<br>道具を決める。</h3></div><p>先に商品名を決めません。条件を入力すると、必要なスペックの範囲と理由を返します。CMSに登録したルールが、そのまま診断ロジックになります。</p></div><div class="condition-ui reveal"><form id="quickCondition"><div class="field-row"><label for="season">Season</label><select id="season" name="season"><option value="spring">春 / 大型</option><option value="autumn">秋 / 数釣り</option></select></div><div class="field-row"><label for="field">Field</label><select id="field" name="field"><option value="port">堤防・漁港</option><option value="rock">磯</option><option value="surf">サーフ</option></select></div><div class="field-row"><label for="depth">Depth</label><select id="depth" name="depth"><option value="shallow">浅場</option><option value="mid">中層</option><option value="deep">深場</option></select></div><div class="field-row"><label for="wind">Wind</label><select id="wind" name="wind"><option value="low">弱い</option><option value="mid">普通</option><option value="strong">強い</option></select></div><div class="field-row"><label for="current">Current</label><select id="current" name="current"><option value="slow">緩い</option><option value="normal">普通</option><option value="fast">速い</option></select></div><button class="cta cta--primary" type="submit">診断する</button><div class="result-panel" id="quickResult" aria-live="polite">条件を選ぶと、推奨レンジと理由を表示します。</div></form></div></div></section>
<section class="section"><div class="section__head reveal"><div><span class="kicker">02 / HOW WE THINK</span><h2>比較より先に、<br>判断基準を。</h2></div><p>このサイトは「人気だから1位」では終わりません。海況と狙いに対して、どのスペックが必要なのかを先に定義します。</p></div><div class="editorial-grid"><article class="editorial-card reveal"><span class="num">01</span><h3>CONDITION</h3><p>季節・水深・風・潮・フィールドを読む。</p><div class="visual"></div></article><article class="editorial-card reveal"><span class="num">02</span><h3>SPEC</h3><p>必要な号数、硬さ、長さ、PE号数へ変換する。</p><div class="visual"></div></article><article class="editorial-card reveal"><span class="num">03</span><h3>GEAR</h3><p>最後に、条件を満たす実在ギアだけを比較する。</p><div class="visual"></div></article></div></section>
<section class="section section--tight"><div class="stat-band reveal"><div class="stat"><b>5</b><span>Core conditions</span></div><div class="stat"><b>8+</b><span>Gear categories</span></div><div class="stat"><b>1</b><span>Shared data source</span></div><div class="stat"><b>0</b><span>Fake field tests</span></div></div></section>
<section class="section"><div class="section__head reveal"><div><span class="kicker">03 / GEAR SYSTEM</span><h2>道具は、<br>単体で選ばない。</h2></div><p>エギ、ロッド、リール、ラインは相互に影響します。単品ランキングではなく、セットとして整合するかを見ます。</p></div><div class="product-rail"><article class="product-card reveal"><div><span class="tag">EGI</span><div class="ghost-gear"><img src="/assets/visuals/gear-orbit.svg" alt="エギ・ロッド・リール・ラインの関係図"></div></div><div><h3>エギ</h3><p>号数、沈下速度、タイプ、姿勢、光量条件から絞り込む。</p><a class="cta" href="/gear.php#egi">見る</a></div></article><article class="product-card reveal"><div><span class="tag">ROD</span><div class="ghost-gear"><img src="/assets/visuals/conditions-map.svg" alt="条件マップ"></div></div><div><h3>ロッド</h3><p>長さとパワーを、飛距離と操作性のトレードオフから選ぶ。</p><a class="cta" href="/gear.php#rod">見る</a></div></article><article class="product-card reveal"><div><span class="tag">SYSTEM</span><div class="ghost-gear"><img src="/assets/visuals/hero-depth.svg" alt="深海の抽象ビジュアル"></div></div><div><h3>一式</h3><p>バランスの取れた一式として、予算と条件で組み合わせる。</p><a class="cta" href="/compare.php">比較する</a></div></article></div></section>
<section class="section"><div class="section__head reveal"><div><span class="kicker">04 / EDITORIAL POLICY</span><h2>売るために、<br>順位を変えない。</h2></div><p>広告報酬と順位は分離します。向かない条件、買わなくていいケース、中古で十分なケースも書きます。</p></div><a class="cta" href="/concept.php#policy">編集方針を見る</a></section>
</main><?php require __DIR__.'/partials/footer.php';?>