<?php
require dirname(__DIR__, 2) . '/app/bootstrap.php'; require_admin();
$types=['egi','rod','reel','pe','leader','snap','landing','bag','light','lifejacket','other'];
if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf((string)($_POST['csrf']??''));$id=(int)($_POST['id']??0);$type=in_array($_POST['type']??'other',$types,true)?$_POST['type']:'other';
$data=[':slug'=>trim($_POST['slug']),':type'=>$type,':brand'=>trim($_POST['brand']),':name'=>trim($_POST['name']),':summary'=>trim($_POST['summary']??''),':price'=>($_POST['price_yen']??'')!==''?(int)$_POST['price_yen']:null,':weight'=>($_POST['weight_g']??'')!==''?(float)$_POST['weight_g']:null,':sink'=>($_POST['sink_sec_per_m']??'')!==''?(float)$_POST['sink_sec_per_m']:null,':source'=>trim($_POST['source_url']??''),':checked'=>($_POST['source_checked_at']??'')?:null,':note'=>trim($_POST['evidence_note']??''),':status'=>in_array($_POST['status']??'draft',['draft','published'],true)?$_POST['status']:'draft'];
if($id){$data[':id']=$id;$pdo->prepare("UPDATE gear_items SET slug=:slug,type=:type,brand=:brand,name=:name,summary=:summary,price_yen=:price,weight_g=:weight,sink_sec_per_m=:sink,source_url=:source,source_checked_at=:checked,evidence_note=:note,status=:status WHERE id=:id")->execute($data);}else{$pdo->prepare("INSERT INTO gear_items(slug,type,brand,name,summary,price_yen,weight_g,sink_sec_per_m,source_url,source_checked_at,evidence_note,status) VALUES(:slug,:type,:brand,:name,:summary,:price,:weight,:sink,:source,:checked,:note,:status)")->execute($data);}header('Location:/admin/gear.php');exit;}
if(isset($_GET['delete'])){verify_csrf((string)($_GET['token']??''));$pdo->prepare("DELETE FROM gear_items WHERE id=?")->execute([(int)$_GET['delete']]);header('Location:/admin/gear.php');exit;}
$edit=null;if(isset($_GET['edit'])){$s=$pdo->prepare("SELECT * FROM gear_items WHERE id=?");$s->execute([(int)$_GET['edit']]);$edit=$s->fetch();}
$rows=$pdo->query("SELECT id,type,brand,name,status,source_checked_at,updated_at FROM gear_items ORDER BY updated_at DESC")->fetchAll();
?><!doctype html><html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>ギア管理</title><style>body{font-family:system-ui;background:#f4f5f6;margin:0}main{max-width:1100px;margin:auto;padding:20px}form,table{background:#fff}form{padding:18px;border:1px solid #ddd;border-radius:12px}label{display:grid;gap:6px;margin:10px 0}input,textarea,select{padding:10px;font:inherit}table{width:100%;border-collapse:collapse;margin-top:20px}th,td{padding:10px;border-bottom:1px solid #eee;text-align:left}</style></head><body><main><?php require __DIR__.'/_nav.php';?><h1>ギア管理</h1><form method="post"><input type="hidden" name="csrf" value="<?=htmlspecialchars(csrf_token(),ENT_QUOTES,'UTF-8')?>"><input type="hidden" name="id" value="<?=(int)($edit['id']??0)?>">
<label>Slug<input required name="slug" value="<?=htmlspecialchars($edit['slug']??'',ENT_QUOTES,'UTF-8')?>"></label><label>種別<select name="type"><?php foreach($types as $t):?><option value="<?=$t?>" <?=($edit['type']??'')===$t?'selected':''?>><?=$t?></option><?php endforeach;?></select></label><label>ブランド<input required name="brand" value="<?=htmlspecialchars($edit['brand']??'',ENT_QUOTES,'UTF-8')?>"></label><label>商品名<input required name="name" value="<?=htmlspecialchars($edit['name']??'',ENT_QUOTES,'UTF-8')?>"></label><label>概要<textarea name="summary"><?=htmlspecialchars($edit['summary']??'',ENT_QUOTES,'UTF-8')?></textarea></label><label>参考価格<input type="number" name="price_yen" value="<?=htmlspecialchars((string)($edit['price_yen']??''),ENT_QUOTES,'UTF-8')?>"></label><label>自重(g)<input step="0.01" type="number" name="weight_g" value="<?=htmlspecialchars((string)($edit['weight_g']??''),ENT_QUOTES,'UTF-8')?>"></label><label>沈下速度 秒/m<input step="0.01" type="number" name="sink_sec_per_m" value="<?=htmlspecialchars((string)($edit['sink_sec_per_m']??''),ENT_QUOTES,'UTF-8')?>"></label><label>出典URL<input type="url" name="source_url" value="<?=htmlspecialchars($edit['source_url']??'',ENT_QUOTES,'UTF-8')?>"></label><label>出典確認日<input type="date" name="source_checked_at" value="<?=htmlspecialchars($edit['source_checked_at']??'',ENT_QUOTES,'UTF-8')?>"></label><label>根拠メモ<textarea name="evidence_note"><?=htmlspecialchars($edit['evidence_note']??'',ENT_QUOTES,'UTF-8')?></textarea></label><label>状態<select name="status"><option value="draft">下書き</option><option value="published" <?=($edit['status']??'')==='published'?'selected':''?>>公開</option></select></label><button>保存</button></form>
<table><tr><th>種別</th><th>ブランド</th><th>商品</th><th>出典確認</th><th>状態</th><th></th></tr><?php foreach($rows as $r):?><tr><td><?=$r['type']?></td><td><?=htmlspecialchars($r['brand'],ENT_QUOTES,'UTF-8')?></td><td><?=htmlspecialchars($r['name'],ENT_QUOTES,'UTF-8')?></td><td><?=$r['source_checked_at']?:'未確認'?></td><td><?=$r['status']?></td><td><a href="?edit=<?=$r['id']?>">編集</a> / <a href="?delete=<?=$r['id']?>&token=<?=urlencode(csrf_token())?>" onclick="return confirm('削除しますか？')">削除</a></td></tr><?php endforeach;?></table></main></body></html>