<?php
require dirname(__DIR__, 2) . '/app/bootstrap.php'; require_admin();
if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf((string)($_POST['csrf']??''));$id=(int)($_POST['id']??0);$output=json_encode(['rod'=>trim($_POST['rod']??''),'egi'=>trim($_POST['egi']??''),'pe'=>trim($_POST['pe']??''),'leader'=>trim($_POST['leader']??'')],JSON_UNESCAPED_UNICODE);
$data=[':priority'=>(int)($_POST['priority']??100),':season'=>($_POST['season']??'')?:null,':field'=>($_POST['field_type']??'')?:null,':depth'=>($_POST['depth_band']??'')?:null,':wind'=>($_POST['wind_band']??'')?:null,':current'=>($_POST['current_band']??'')?:null,':size'=>($_POST['target_size']??'')?:null,':output'=>$output,':rationale'=>trim($_POST['rationale']??''),':source'=>trim($_POST['source_note']??''),':enabled'=>isset($_POST['enabled'])?1:0];
if($id){$data[':id']=$id;$pdo->prepare("UPDATE simulator_rules SET priority=:priority,season=:season,field_type=:field,depth_band=:depth,wind_band=:wind,current_band=:current,target_size=:size,output=:output,rationale=:rationale,source_note=:source,enabled=:enabled WHERE id=:id")->execute($data);}else{$pdo->prepare("INSERT INTO simulator_rules(priority,season,field_type,depth_band,wind_band,current_band,target_size,output,rationale,source_note,enabled) VALUES(:priority,:season,:field,:depth,:wind,:current,:size,:output,:rationale,:source,:enabled)")->execute($data);}header('Location:/admin/rules.php');exit;}
if(isset($_GET['delete'])){verify_csrf((string)($_GET['token']??''));$pdo->prepare("DELETE FROM simulator_rules WHERE id=?")->execute([(int)$_GET['delete']]);header('Location:/admin/rules.php');exit;}
$edit=null;if(isset($_GET['edit'])){$s=$pdo->prepare("SELECT * FROM simulator_rules WHERE id=?");$s->execute([(int)$_GET['edit']]);$edit=$s->fetch();if($edit){$edit['out']=json_decode($edit['output'],true)?:[];}}
$rows=$pdo->query("SELECT id,priority,season,field_type,depth_band,wind_band,current_band,enabled,updated_at FROM simulator_rules ORDER BY priority,id")->fetchAll();
?><!doctype html><html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>診断ルール管理</title><style>body{font-family:system-ui;background:#f4f5f6;margin:0}main{max-width:1100px;margin:auto;padding:20px}form,table{background:#fff}form{padding:18px;border:1px solid #ddd;border-radius:12px}label{display:grid;gap:6px;margin:10px 0}input,textarea,select{padding:10px;font:inherit}table{width:100%;border-collapse:collapse;margin-top:20px}th,td{padding:9px;border-bottom:1px solid #eee;text-align:left}</style></head><body><main><?php require __DIR__.'/_nav.php';?><h1>診断ルール管理</h1><form method="post"><input type="hidden" name="csrf" value="<?=htmlspecialchars(csrf_token(),ENT_QUOTES,'UTF-8')?>"><input type="hidden" name="id" value="<?=(int)($edit['id']??0)?>">
<label>優先度<input type="number" name="priority" value="<?=htmlspecialchars((string)($edit['priority']??100),ENT_QUOTES,'UTF-8')?>"></label>
<label>季節<input name="season" placeholder="spring / autumn / 空欄=共通" value="<?=htmlspecialchars($edit['season']??'',ENT_QUOTES,'UTF-8')?>"></label><label>フィールド<input name="field_type" placeholder="port / rock / surf" value="<?=htmlspecialchars($edit['field_type']??'',ENT_QUOTES,'UTF-8')?>"></label><label>水深<input name="depth_band" placeholder="shallow / mid / deep" value="<?=htmlspecialchars($edit['depth_band']??'',ENT_QUOTES,'UTF-8')?>"></label><label>風<input name="wind_band" placeholder="low / mid / strong" value="<?=htmlspecialchars($edit['wind_band']??'',ENT_QUOTES,'UTF-8')?>"></label><label>潮<input name="current_band" placeholder="slow / normal / fast" value="<?=htmlspecialchars($edit['current_band']??'',ENT_QUOTES,'UTF-8')?>"></label><label>対象サイズ<input name="target_size" value="<?=htmlspecialchars($edit['target_size']??'',ENT_QUOTES,'UTF-8')?>"></label>
<label>ロッド<input name="rod" value="<?=htmlspecialchars($edit['out']['rod']??'',ENT_QUOTES,'UTF-8')?>"></label><label>エギ<input name="egi" value="<?=htmlspecialchars($edit['out']['egi']??'',ENT_QUOTES,'UTF-8')?>"></label><label>PE<input name="pe" value="<?=htmlspecialchars($edit['out']['pe']??'',ENT_QUOTES,'UTF-8')?>"></label><label>リーダー<input name="leader" value="<?=htmlspecialchars($edit['out']['leader']??'',ENT_QUOTES,'UTF-8')?>"></label><label>理由<textarea required name="rationale"><?=htmlspecialchars($edit['rationale']??'',ENT_QUOTES,'UTF-8')?></textarea></label><label>根拠メモ<textarea name="source_note"><?=htmlspecialchars($edit['source_note']??'',ENT_QUOTES,'UTF-8')?></textarea></label><label><input type="checkbox" name="enabled" <?=($edit['enabled']??1)?'checked':''?>> 有効</label><button>保存</button></form>
<table><tr><th>優先</th><th>季節</th><th>場所</th><th>水深</th><th>風</th><th>潮</th><th>有効</th><th></th></tr><?php foreach($rows as $r):?><tr><td><?=$r['priority']?></td><td><?=$r['season']?:'*'?></td><td><?=$r['field_type']?:'*'?></td><td><?=$r['depth_band']?:'*'?></td><td><?=$r['wind_band']?:'*'?></td><td><?=$r['current_band']?:'*'?></td><td><?=$r['enabled']?'ON':'OFF'?></td><td><a href="?edit=<?=$r['id']?>">編集</a> / <a href="?delete=<?=$r['id']?>&token=<?=urlencode(csrf_token())?>" onclick="return confirm('削除しますか？')">削除</a></td></tr><?php endforeach;?></table></main></body></html>